# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-27 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('latitude', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Chains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='branches',
            name='chain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Chains'),
        ),
    ]
